# Generated by Django 5.1.2 on 2024-12-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default=0, upload_to='cars/'),
            preserve_default=False,
        ),
    ]
